services:
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.11.0
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OpenTelemetry gRPC
      - "4318:4318" # OpenTelemetry HTTP
      - "5778:5778" # Configuration service
      - "9411:9411" # Zipkin compatibility
      - "6831:6831/udp"
    restart: unless-stopped
